name: ESLint
on:
  - push
  - pull_request
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ github.repository }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-node-modules-
    - if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        # Install Dependencies if no cache-hit
        yarn install
    - run: yarn lint:run
